#Setup BES3 Offline Software System(BOSS)
name: SetupBOSS

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setupBOSS:
    runs-on: ubuntu-latest

    # run docker of centos containing cvmfs. Then mount the BOSS to /cvmfs. Finally, set the environment for boss
    steps:
      - run: docker image pull barbohrben/boss:c
      - run: sudo docker container run --privileged  --rm -it barbohrben/boss:c bin/bash
    #Mount the BOSS to /cvmfs
      - run: sudo mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch 
      - run: sudo mount -t cvmfs container.ihep.ac.cn /cvmfs/container.ihep.ac.cn 
      - run: sudo mount -t cvmfs bes3.ihep.ac.cn /cvmfs/bes3.ihep.ac.cn
      
    #Set the environment for boss
      - run: cd ~&&mkdir cmthome
      - run: cd cmthome
      - run: cp /cvmfs/bes3.ihep.ac.cn/bes3sw/cmthome/cmthome-7.0.8/* ~/cmthome/
      - run: source setupCMT.sh
      - run: cmt config&&source setup.sh
      
    #Run Helloworld
      - run: cd /cvmfs/bes3.ihep.ac.cn/bes3sw/Boss/7.0.8/TestRelease/TestRelease-00-00-95/cmt/
      - run: source setup.sh
      - run: cd ../run&&boss.exe HelloWorldOptions.txt
