#Setup BES3 Offline Software System(BOSS)
name: SetupBOSS

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setupBOSS:
    runs-on: ubuntu-latest

    # run docker of centos containing cvmfs. Then mount the BOSS to /cvmfs. Finally, set the environment for boss
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: source setup708.sh
      - run: ls -a
      - run: source remake.sh
