#Setup BES3 Offline Software System(BOSS)
name: SetupBOSS

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setupBOSS:
    runs-on: ubuntu-latest

    # run docker of centos containing cvmfs. Then mount the BOSS to /cvmfs. Finally, set the environment for boss
    steps:
      - run: docker image pull barbohrben/boss:complete
      - run: docker container run -d --name boss --privileged barbohrben/boss:complete sleep 1d
    #Mount the BOSS to /cvmfs
      - run: docker container exec boss mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch
      - run: docker container exec boss mount -t cvmfs container.ihep.ac.cn /cvmfs/container.ihep.ac.cn 
      - run: docker container exec boss mount -t cvmfs bes3.ihep.ac.cn /cvmfs/bes3.ihep.ac.cn
      
    #Set the environment for boss
      - run: docker container exec boss /bin/bash -c 'echo "cd /home" | sudo tee  /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "mkdir cmthome&&mkdir TestRelease"  | sudo tee -a /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "cd cmthome"  | sudo tee -a /home/setup708.sh'
     # - run: docker container exec boss cd /cvmfs/bes3.ihep.ac.cn/bes3sw/cmthome/cmthome-7.0.8'
      - run: docker container exec boss /bin/bash -c 'echo "cp /cvmfs/bes3.ihep.ac.cn/bes3sw/cmthome/cmthome-7.0.8/* /home/cmthome/"  | sudo tee -a /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "source setupCMT.sh"  | sudo tee -a /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "cmt config&&source setup.sh"  | sudo tee -a /home/setup708.sh'
      
    #Run
      - run: docker container exec boss /bin/bash -c 'echo "cp -r /cvmfs/bes3.ihep.ac.cn/bes3sw/Boss/7.0.8/TestRelease/TestRelease-00-00-95/* /home/TestRelease"  | sudo tee -a /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "cd /home/TestRelease/cmt"  | sudo tee -a /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "source setup.sh"  | sudo tee -a /home/setup708.sh'
      - run: docker container exec boss /bin/bash -c 'echo "cd ../run&&boss.exe jobOptions_ana_pipijpsi.txt"  | sudo tee -a /home/setup708.sh'

      - run: docker container exec boss /bin/bash -c 'source /home/setup708.sh'
